name: Build & Publish Eating Asturias

on:
  push:
    branches:
      -master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.3

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll
        run: |
          bundle exec jekyll build

      - name: Deploy Site
        uses: wlixcc/SFTP-Deploy-Action@v1.2.5
        with:
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: './_site/*'
          remote_path: '/home/eatingas/staging.eatingasturias.com'
          sftp_only: true
          sftpArgs: '-o ConnectTimeout=5'